seed: 0
run_name: default  # Change this for each run (or reuse to start from checkpoint)
wandb_track: False
log_every_n_steps: 5
accelerator: auto  # Device for training (used by pytorch_lightning)
num_devices: 1  # Number of devices to use for training (NOTE: multi-gpu training not supported yet)
max_steps: 70000
lr_warmup_steps: 500
val_freq: 1  # Check val every x epochs
train_batch_size: 2 
val_batch_size: 2
train_data_fraction: 1.0 # 0.25
val_data_fraction: 0.25
precision: 32-true # bf16-mixed for bfloat16 mixed precision or 32-true for regular
gradient_clip_val: 1.0  # TODO: TBD if this is a reasonable value
lr: 5e-4
weight_decay: 1e-4
data_root: /network/scratch/x/xuolga/Datasets  # /network/scratch/x/xuolga/Datasets /network/scratch/a/anthony.gosselin/Datasets
dataset: kitti  # [kitti, vkitti, bdd100k]
dataloader_workers: 2
save_top_k_checkpoints: 7
dataset_non_overlapping: False
smooth_gt_leaving_frame: False

# Conditioning
condition_last_frame: True # False
initial_frames_condition_num: 3 # 1
only_keep_initial_agents: True # False
always_predict_initial_agents: False  # This means we assume initial agents will always exist and keep predicting their position (even if they move out of frame)
use_state_embeddings: True
map_embedding: True
last_frame_traj: False

# Transformer model config
state_dim: 4  # {x1, y1, x2, y2}
hidden_dim: 256 # TBD: {32, 64, 256, 512}
dim_feedforward: 1024
num_heads: 8
num_decoder_layers: 4
num_encoder_layers: 2
dir_disc: 24  # Discretization resolution
norm_disc: 16 # Discretization resolution
vocabulary_size: 384 # This value will be updated automatically according to the two above (dir_disc * norm_disc)

num_timesteps: 25  # AKA "clip_length" (number of frames per video)
max_num_agents: 15  # To be changed according to MAX_BOXES_PER_DATA (ctrlv/datasets/__init__.py)
video_fps: 7
num_demo_samples: 1
train_W: 512
train_H: 320

action_temp: 1.0  # Temperature for sampling
model_path: /home/mila/a/anthony.gosselin/wandb/diffuser/config21_2/last.ckpt
disable_image_load: False
load_bbox_image: False
num_eval_samples: 1
teacher_force_eval: False
eval_videos_every: -1